### ISSUE TITLE
make error when running jade

### ISSUE THREAD

**Issue by Mishkakay** [orcc/jade#4]
CMake Error at CMakeLists.txt:37 (message):
  The LLVM_CONFIG_TOOL variable have an invalid value.  It must contains the
  full path of llvm-config executable.

-- Configuring incomplete, errors occurred!
See also "/home/chevounne/jade/build/CMakeFiles/CMakeOutput.log".
See also "/home/chevounne/jade/build/CMakeFiles/CMakeError.log".

**Comment by hyviquel** [comment]
Are you sure to have followed the installation instructions:
https://github.com/orcc/jade/blob/master/README.md

**Comment by Mishkakay** [comment]
Good day,
yes I have done everything the instructions have said and to make sure it
is done properly, I installed everything from the terminal with apt-get. I
have been trying for 3 weeks now. I have deleted the files and start over
and always getting an error when I am suppose to run the make command to
install Jade.

Chevounne Getten
University of Technology Jamaica
chevkay@gmail.com
<http://goog_535946363>
chevounneg@yahoo.com

**Comment by mraulet** [comment]
Can you run llvm-config from the terminal?

Mickael

Sent by my iPhone

**Comment by hyviquel** [comment]
... and can you show us the result ?

**Comment by Mishkakay** [comment]
Here is what I got when i ran llvm-config
usage: llvm-config <OPTION>... [<COMPONENT>...]

Get various configuration information needed to compile programs which use
LLVM.  Typically called from 'configure' scripts.  Examples:
  llvm-config --cxxflags
  llvm-config --ldflags
  llvm-config --libs engine bcreader scalaropts

Options:
  --version         Print LLVM version.
  --prefix          Print the installation prefix.
  --src-root        Print the source root LLVM was built from.
  --obj-root        Print the object root used to build LLVM.
  --bindir          Directory containing LLVM executables.
  --includedir      Directory containing LLVM headers.
  --libdir          Directory containing LLVM libraries.
  --cppflags        C preprocessor flags for files that include LLVM headers.
  --cflags          C compiler flags for files that include LLVM headers.
  --cxxflags        C++ compiler flags for files that include LLVM headers.
  --ldflags         Print Linker flags.
  --libs            Libraries needed to link against LLVM components.
  --libnames        Bare library names for in-tree builds.
  --libfiles        Fully qualified library filenames for makefile depends.
  --components      List of all possible components.
  --targets-built   List of all targets currently built.
  --host-target     Target triple used to configure LLVM.
  --build-mode      Print build mode of LLVM tree (e.g. Debug or Release).
Typical components:
  all               All LLVM libraries (default).
  engine            Either a native JIT or a bitcode interpreter.

**Comment by hyviquel** [comment]
Ok, llvm_config seems accessible from your terminal but CMake seems unable to find it...
Have you run cmake from your terminal as well ?

**Comment by hyviquel** [comment]
is "llvm_config" accessible directly from your $PATH ?

**Comment by mraulet** [comment]
And what does llvm-config say when you run llvm-config --version ?

Mickael

Sent by my iPhone

**Comment by alorence** [comment]
llvm-config has been found by CMake on your computer, but the execution of 'llvm-config --version' returned an empty string. Can you paste here the result of this command when you type it in your terminal ?

**Comment by Mishkakay** [comment]
3.2svn

**Comment by Mishkakay** [comment]
yes  I ran cmake .. and i

**Comment by mraulet** [comment]
Do you need to use llvm from sources?

You should install Llvm where it is supposed to be. I suppose Cmake might be looking for /usr/local/bin.

Another solution is to:

sudo apt-get install llvm-devel 
Or something equivalent.

**Comment by alorence** [comment]
Another important information: the error message you obtain indicates that you try to compile Jade from sources on branch `master`or `llvm_3.4`. Your LLVM version is 3.2. To compile Jade, you have to checkout the sources of branch `llvm_3.2`or compile and install the LLVM 3.5 (the latest version supported).

And +1 on @mraulet comment: you should run `make install` after LLVM compilation or install LLVM from your package manager.

**Comment by mraulet** [comment]
can we close? any updates?

**Comment by Mishkakay** [comment]
Yes you can and thanks for all your help. It still hasn't worked so I moved
on to clang.

Chevounne Getten
University of Technology Jamaica
chevkay@gmail.com
http://goog_535946363
chevounneg@yahoo.com
